blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/VB317/GeminiProChat/discussions
    about: Use discussions if you have an idea for improvement or for asking questions.